[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
]
ffi = true #never do this in real project as this command means we are allowing foundry to run commands directly on my local machine

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
